---
title: "hackathon"
author: "A Team Has No Name: Yuyang Zhang, Jenny Zhen, Li Cao"
date: "6/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp)
library(TSA)
library(ggplot2)
```

## Step 1. Load data and exploratory data

```{r}
datapath<-"~/Desktop/data"
df_il<-read.csv(file=paste(datapath,"df_il.csv",sep="/"),header=TRUE,sep=",")
df_il
```

```{r}
confirmed_cases <- ts(df_il$confirmed_cases, start=1/7, frequency=7)
confirmed_cases <- log(confirmed_cases)
autoplot(confirmed_cases,color = "darkblue")+ xlab("Date") + ggtitle("Log of Confirmed Cases")

confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
autoplot(confirmed_cases_train,color = "darkblue")+ xlab("Date") + ggtitle("Log of Confirmed Cases  (train dataset)")

confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
autoplot(confirmed_cases_test,color = "darkblue")+ xlab("Date") + ggtitle("Log of Confirmed Cases (test dataset)")
confirmed_cases_mean <- mean(confirmed_cases_test)
```

## Step 2. ARIMAX - Retail and recreation

```{r}
policyRetail <- ts(df_il$policyScore_retail, start=1/7, frequency=7)
autoplot(policyRetail,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Retail")

policyRetail_train <- window(policyRetail, start=1/7, end=100/7)
autoplot(policyRetail_train,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Retail (train dataset)")

policyRetail_test <- window(policyRetail, start=101/7, end=107/7)
autoplot(policyRetail_test,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Retail (test dataset)")

policyRetail_mean <- mean(policyRetail_test)
```

```{r}
mobilityRetail <- ts(df_il$retail_and_recreation, start=1/7, frequency=7)
autoplot(mobilityRetail,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Retail and Recreation")

mobilityRetail_train <- window(mobilityRetail, start=8/7, end=107/7)
autoplot(mobilityRetail_train,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Retail and Recreation  (train dataset)")

mobilityRetail_test <- window(mobilityRetail, start=108/7, end=114/7)
autoplot(mobilityRetail_test,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Retail and Recreation (test dataset)")
```

```{r}
fit_Regression_ARMA_retail <- auto.arima(mobilityRetail_train, seasonal = FALSE, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyRetail_train))
summary(fit_Regression_ARMA_retail)
checkresiduals(fit_Regression_ARMA_retail)

forecast_Regression_ARMA_retail <- forecast(fit_Regression_ARMA_retail, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyRetail_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_retail, mobilityRetail_test)

plot(forecast_Regression_ARMA_retail, col=1, include=12)
lines(mobilityRetail_test, type="l",col=2)
```


## Step 3. ARIMAX - Grocery and pharmacy

```{r}
policyGrocery <- ts(df_il$policyScore_grocery, start=1/7, frequency=7)
policyGrocery_train <- window(policyGrocery, start=1/7, end=100/7)
policyGrocery_test <- window(policyGrocery, start=101/7, end=107/7)
policyGrocery_mean <- mean(policyGrocery_test)
autoplot(policyGrocery,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Grocery")

mobilityGrocery <- ts(df_il$grocery_and_pharmacy, start=1/7, frequency=7)
mobilityGrocery_train <- window(mobilityGrocery, start=8/7, end=107/7)
mobilityGrocery_test <- window(mobilityGrocery, start=108/7, end=114/7)
autoplot(mobilityGrocery,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Grocery and pharmacy")

fit_Regression_ARMA_grocery <- auto.arima(mobilityGrocery_train, seasonal = FALSE, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyGrocery_train))
summary(fit_Regression_ARMA_grocery)
checkresiduals(fit_Regression_ARMA_grocery)

forecast_Regression_ARMA_grocery <- forecast(fit_Regression_ARMA_grocery, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyGrocery_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_grocery, mobilityGrocery_test)

plot(forecast_Regression_ARMA_grocery, col=1, include=12)
lines(mobilityGrocery_test, type="l",col=2)
```


## Step 4. ARIMAX - Parks

```{r}
policyParks <- ts(df_il$policyScore_parks, start=1/7, frequency=7)
policyParks_train <- window(policyParks, start=1/7, end=100/7)
policyParks_test <- window(policyParks, start=101/7, end=107/7)
policyParks_mean <- mean(policyParks_test)
autoplot(policyParks,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Parks")

mobilityParks <- ts(df_il$parks, start=1/7, frequency=7)
mobilityParks_train <- window(mobilityParks, start=8/7, end=107/7)
mobilityParks_test <- window(mobilityParks, start=108/7, end=114/7)
autoplot(mobilityParks,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Parks")

fit_Regression_ARMA_parks <- auto.arima(mobilityParks_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyParks_train))
summary(fit_Regression_ARMA_parks)
checkresiduals(fit_Regression_ARMA_parks)

forecast_Regression_ARMA_parks <- forecast(fit_Regression_ARMA_parks, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyParks_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_parks, mobilityParks_test)

plot(forecast_Regression_ARMA_parks, col=1, include=12)
lines(mobilityParks_test, type="l",col=2)
```


## Step 5. ARIMAX - Transit

```{r}
policyTransit <- ts(df_il$policyScore_transit, start=1/7, frequency=7)
policyTransit_train <- window(policyTransit, start=1/7, end=100/7)
policyTransit_test <- window(policyTransit, start=101/7, end=107/7)
policyTransit_mean <- mean(policyTransit_test)
autoplot(policyTransit,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Transit")

mobilityTransit <- ts(df_il$transit_stations, start=1/7, frequency=7)
mobilityTransit_train <- window(mobilityTransit, start=8/7, end=107/7)
mobilityTransit_test <- window(mobilityTransit, start=108/7, end=114/7)
autoplot(mobilityTransit,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Transit")

fit_Regression_ARMA_transit <- auto.arima(mobilityTransit_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyTransit_train))
summary(fit_Regression_ARMA_transit)
checkresiduals(fit_Regression_ARMA_transit)

forecast_Regression_ARMA_transit <- forecast(fit_Regression_ARMA_transit, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyTransit_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_transit, mobilityTransit_test)

plot(forecast_Regression_ARMA_transit, col=1, include=12)
lines(mobilityTransit_test, type="l",col=2)
```


## Step 6. ARIMAX - Workplaces

```{r}
policyWorkplaces <- ts(df_il$policyScore_workplaces, start=1/7, frequency=7)
policyWorkplaces_train <- window(policyWorkplaces, start=1/7, end=100/7)
policyWorkplaces_test <- window(policyWorkplaces, start=101/7, end=107/7)
policyWorkplaces_mean <- mean(policyWorkplaces_test)
autoplot(policyWorkplaces,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Workplaces")

mobilityWorkplaces <- ts(df_il$workplaces, start=1/7, frequency=7)
mobilityWorkplaces_train <- window(mobilityWorkplaces, start=8/7, end=107/7)
mobilityWorkplaces_test <- window(mobilityWorkplaces, start=108/7, end=114/7)

autoplot(mobilityWorkplaces,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Workplaces")
autoplot(mobilityWorkplaces_train,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Workplaces (train dataset)")
autoplot(mobilityWorkplaces_test,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Workplaces (test dataset)")

par(mfrow=c(3,1))
plot(mobilityWorkplaces)
Acf(mobilityWorkplaces)
pacf(mobilityWorkplaces)

mobilityWorkplaces_seasondiff = diff(mobilityWorkplaces,lag=7)
par(mfrow=c(3,1))
plot(mobilityWorkplaces_seasondiff)
Acf(mobilityWorkplaces_seasondiff)
pacf(mobilityWorkplaces_seasondiff)

mobilityWorkplaces_seasondiff_diff = diff(mobilityWorkplaces,lag=1)
par(mfrow=c(3,1))
plot(mobilityWorkplaces_seasondiff_diff)
Acf(mobilityWorkplaces_seasondiff_diff)
pacf(mobilityWorkplaces_seasondiff_diff)

kpss.test(mobilityWorkplaces)
adf.test(mobilityWorkplaces)

kpss.test(mobilityWorkplaces_seasondiff)
adf.test(mobilityWorkplaces_seasondiff)

kpss.test(mobilityWorkplaces_seasondiff_diff) # p-value = 0.1 > 0.05 ==> Accept Null hypothesis ==> The process is stationary. 
adf.test(mobilityWorkplaces_seasondiff_diff) # p-value = 0.01 < 0.05 ==> Accept alternative hypothesis ==> The process is stationary. 


fit_Regression_ARMA_workplaces <- auto.arima(mobilityWorkplaces_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyWorkplaces_train))

forecast_Regression_ARMA_workplaces <- forecast(fit_Regression_ARMA_workplaces, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyWorkplaces_mean,7)), h=7)

summary(fit_Regression_ARMA_workplaces)
checkresiduals(fit_Regression_ARMA_workplaces)
accuracy(forecast_Regression_ARMA_workplaces, mobilityWorkplaces_test)

plot(forecast_Regression_ARMA_workplaces, col=1, include=12)
lines(mobilityWorkplaces_test, type="l",col=2)

```

```{r}
policyWorkplaces <- ts(df_il$policyScore_workplaces, start=1/7, frequency=7)
policyWorkplaces_train <- window(policyWorkplaces, start=1/7, end=100/7)
policyWorkplaces_test <- window(policyWorkplaces, start=101/7, end=107/7)
policyWorkplaces_mean <- mean(policyWorkplaces_test)
autoplot(policyWorkplaces,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Workplaces")

mobilityWorkplaces <- ts(df_il$workplaces, start=1/7, frequency=7)
mobilityWorkplaces_train <- window(mobilityWorkplaces, start=8/7, end=107/7)
mobilityWorkplaces_test <- window(mobilityWorkplaces, start=108/7, end=114/7)
autoplot(mobilityWorkplaces,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Workplaces")

fit_Regression_ARMA_workplaces <- auto.arima(mobilityWorkplaces_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyWorkplaces_train))
summary(fit_Regression_ARMA_workplaces)
checkresiduals(fit_Regression_ARMA_workplaces)

forecast_Regression_ARMA_workplaces <- forecast(fit_Regression_ARMA_workplaces, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyWorkplaces_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_workplaces, mobilityWorkplaces_test)

plot(forecast_Regression_ARMA_workplaces, col=1, include=12)
lines(mobilityWorkplaces_test, type="l",col=2)
```


## Step 7. ARIMAX - Residential

```{r}
policyResidential <- ts(df_il$policyScore_residential, start=1/7, frequency=7)
policyResidential_train <- window(policyResidential, start=1/7, end=100/7)
policyResidential_test <- window(policyResidential, start=101/7, end=107/7)
policyResidential_mean <- mean(policyResidential_test)
autoplot(policyResidential,color = "darkblue")+ xlab("Date") + ggtitle("PolicyScore_Residential")

mobilityResidential <- ts(df_il$residential, start=1/7, frequency=7)
mobilityResidential_train <- window(mobilityResidential, start=8/7, end=107/7)
mobilityResidential_test <- window(mobilityResidential, start=108/7, end=114/7)
autoplot(mobilityResidential,color = "darkblue")+ xlab("Date") + ylab("Percentage")+ggtitle("Residential")

fit_Regression_ARMA_residential <- auto.arima(mobilityResidential_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyResidential_train))
summary(fit_Regression_ARMA_residential)
checkresiduals(fit_Regression_ARMA_residential)

forecast_Regression_ARMA_residential <- forecast(fit_Regression_ARMA_residential, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyResidential_mean,7)), h=7)
accuracy(forecast_Regression_ARMA_residential, mobilityResidential_test)

plot(forecast_Regression_ARMA_residential, col=1, include=12)
lines(mobilityResidential_test, type="l",col=2)
```


## Step 8. Summary

```{r}
c = cbind(forecast_Regression_ARMA_retail$mean, forecast_Regression_ARMA_grocery$mean, forecast_Regression_ARMA_parks$mean,forecast_Regression_ARMA_transit$mean, forecast_Regression_ARMA_workplaces$mean, forecast_Regression_ARMA_residential$mean)
colnames(c) <- c("retail","grocery","parks","transit","workplaces","residential")
#write.csv(c, 'forecast.csv')
c
```










