---
title: "Arimax_States"
author: "Li Cao"
date: "6/19/2020"
output: html_document
---


```{r}
df_us<-read.csv('/Users/li/Desktop/MsCA/hack_COVID19/covid19_us_summary_imputation.csv')
df_us




# retail
retail_weights_df<-read.csv("retail_policy_scores.csv")
retail_weights_df<-retail_weights_df[1:5814,]


state_list=unique(df_us$a_state)
results=list()
rmse_retail=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=retail_weights_df[which(retail_weights_df$a_state==i),]
  policyRetail <- ts(state_weight$policyScore_retail, start=1/7, frequency=7)
  policyRetail_train <- window(policyRetail, start=1/7, end=100/7)
  policyRetail_test <- window(policyRetail, start=101/7, end=107/7)
  policyRetail_mean <- mean(policyRetail_test)
# mobile data
  mobilityRetail <- ts(data_frame_state$retail_and_recreation, start=1/7, end = 114/7, frequency=7)
  mobilityRetail_train <- window(mobilityRetail, start=8/7, end=107/7)
  mobilityRetail_test <- window(mobilityRetail, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_retail <- auto.arima(mobilityRetail_train, seasonal = FALSE,trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyRetail_train))
  
  # predict
  forecast_Regression_ARMA_retail <- forecast(fit_Regression_ARMA_retail, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyRetail_mean,7)), h=7)
  
  # results
  results_rmse=accuracy(forecast_Regression_ARMA_retail, mobilityRetail_test)
  results_rmse=cbind(c(paste(i,"train set"),paste(i,"test set")),results_rmse)
  rmse_retail=rbind(rmse_retail,results_rmse)
  results_i=forecast_Regression_ARMA_retail$mean
  results=rbind(results,results_i)
  
}



```

```{r}
results
results_table<-data.frame(matrix(unlist(results), ncol=7,byrow = F))     

results_table["State"]=state_list
results_table
colnames(results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")
results_table
write.csv(results_table,"Retail_prediction7_all_States.csv")
```


```{r}
results_rmse_table<-data.frame(matrix(unlist(rmse_retail), ncol=9,byrow = F))      

colnames(results_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

results_rmse_table
write.csv(results_rmse_table,"Retail_Rmse_all_States.csv")
```




```{r}

# grocery
grocery_weights_df<-read.csv("grocery_policy_scores.csv")

# test AL 

grocery_results=list()
grocery_rmse=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=grocery_weights_df[which(grocery_weights_df$a_state==i),]
  policyGrocery <- ts(state_weight$policyScore_grocery, start=1/7, frequency=7)
  policyGrocery_train <- window(policyGrocery, start=1/7, end=100/7)
  policyGrocery_test <- window(policyGrocery, start=101/7, end=107/7)
  policyGrocery_mean <- mean(policyGrocery_test)
# mobile data
  mobilityGrocery <- ts(data_frame_state$grocery_and_pharmacy, start=1/7, end = 114/7, frequency=7)
  mobilityGrocery_train <- window(mobilityGrocery, start=8/7, end=107/7)
  mobilityGrocery_test <- window(mobilityGrocery, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_grocery <- auto.arima(mobilityGrocery_train,seasonal = FALSE, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyGrocery_train))
  
  # predict
  forecast_Regression_ARMA_grocery <- forecast(fit_Regression_ARMA_grocery, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyGrocery_mean,7)), h=7)
  
  # results for measures 
  results_i=accuracy(forecast_Regression_ARMA_grocery, mobilityGrocery_test)
  results_i=cbind(c(paste(i,"train set"),paste(i,"test set")),results_i)
  grocery_rmse=rbind(grocery_rmse,results_i)

#  prediction
  grocery_results=rbind(grocery_results,forecast_Regression_ARMA_grocery$mean)

}







```

```{r}
grocery_results_table<-data.frame(matrix(unlist(grocery_results), ncol=7,byrow = F))     
grocery_results_table
grocery_results_table["State"]=state_list
grocery_results_table
colnames(grocery_results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")

write.csv(grocery_results_table,"Grocery_prediction7_all_States.csv")
```


```{r}
grocery_rmse_table<-data.frame(matrix(unlist(grocery_rmse), ncol=9,byrow = F))      

colnames(grocery_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

grocery_rmse_table
write.csv(grocery_rmse_table,"Grocery_Rmse_all_States.csv")
```






```{r}
residential_weights_df<-read.csv("residential_policy_scores.csv")

# test AL 

residential_results=list()
residential_rmse=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=residential_weights_df[which(residential_weights_df$a_state==i),]
  policyresidential <- ts(state_weight$policyScore_residential, start=1/7, frequency=7)
  policyresidential_train <- window(policyresidential, start=1/7, end=100/7)
  policyresidential_test <- window(policyresidential, start=101/7, end=107/7)
  policyresidential_mean <- mean(policyresidential_test)
# mobile data
  mobilityresidential <- ts(data_frame_state$residential, start=1/7, end = 114/7, frequency=7)
  mobilityresidential_train <- window(mobilityresidential, start=8/7, end=107/7)
  mobilityresidential_test <- window(mobilityresidential, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_residential <- auto.arima(mobilityresidential_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyresidential_train))
  
  # predict
  forecast_Regression_ARMA_residential <- forecast(fit_Regression_ARMA_residential, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyresidential_mean,7)), h=7)
  
  # results rmse 
  results_i=accuracy(forecast_Regression_ARMA_residential, mobilityresidential_test)
  results_i=cbind(c(paste(i,"train set"),paste(i,"test set")),results_i)
  residential_rmse=rbind(residential_rmse,results_i)
  # results for predictions
  residential_results=rbind(residential_results,forecast_Regression_ARMA_residential$mean)
  
}

```

```{r}
residential_results

residential_results_table<-data.frame(matrix(unlist(residential_results), ncol=7,byrow = F))     
residential_results_table
residential_results_table["State"]=state_list
residential_results_table
colnames(residential_results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")

write.csv(residential_results_table,"Residential_prediction7_all_States.csv")
```


```{r}
residential_rmse_table<-data.frame(matrix(unlist(residential_rmse), ncol=9,byrow = F))      

colnames(residential_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

residential_rmse_table
write.csv(residential_rmse_table,"Residential_Rmse_all_States.csv")
```





```{r}
transit_weights_df<-read.csv("transit_policy_scores.csv")

# test AL 

transit_results=list()
transit_rmse=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=transit_weights_df[which(transit_weights_df$a_state==i),]
  policyTransit <- ts(state_weight$policyScore_transit, start=1/7, frequency=7)
  policyTransit_train <- window(policyTransit, start=1/7, end=100/7)
  policyTransit_test <- window(policyTransit, start=101/7, end=107/7)
  policyTransit_mean <- mean(policyTransit_test)
# mobile data
  mobilityTransit <- ts(data_frame_state$transit_stations, start=1/7, end = 114/7, frequency=7)
  mobilityTransit_train <- window(mobilityTransit, start=8/7, end=107/7)
  mobilityTransit_test <- window(mobilityTransit, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_Transit <- auto.arima(mobilityTransit_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyTransit_train))
  
  # predict
  forecast_Regression_ARMA_Transit <- forecast(fit_Regression_ARMA_Transit, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyTransit_mean,7)), h=7)
  
  # results rmse
  results_i=accuracy(forecast_Regression_ARMA_Transit, mobilityTransit_test)
  results_i=cbind(c(paste(i,"train set"),paste(i,"test set")),results_i)
  transit_rmse=rbind(transit_rmse,results_i)
  # results for prediction
  transit_results=rbind(transit_results,forecast_Regression_ARMA_Transit$mean)
  
}
```



```{r}

transit_results_table<-data.frame(matrix(unlist(transit_results), ncol=7,byrow = F))     
transit_results_table
transit_results_table["State"]=state_list
transit_results_table
colnames(transit_results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")

write.csv(transit_results_table,"Transit_prediction7_all_States.csv")
```

```{r}
transit_rmse_table<-data.frame(matrix(unlist(transit_rmse), ncol=9,byrow = F))      

colnames(transit_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

transit_rmse_table
write.csv(transit_rmse_table,"Transit_Rmse_all_States.csv")
```



```{r}
# workplace 
workplace_weights_df<-read.csv("workplaces_policy_scores.csv")

# test AL 

workplace_results=list()
workplace_rmse=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=workplace_weights_df[which(workplace_weights_df$a_state==i),]
  policyWorkplace <- ts(state_weight$policyScore_workplaces, start=1/7, frequency=7)
  policyWorkplace_train <- window(policyWorkplace, start=1/7, end=100/7)
  policyWorkplace_test <- window(policyWorkplace, start=101/7, end=107/7)
  policyWorkplace_mean <- mean(policyWorkplace_test)
# mobile data
  mobilityWorkplace <- ts(data_frame_state$workplaces, start=1/7, end = 114/7, frequency=7)
  mobilityWorkplace_train <- window(mobilityWorkplace, start=8/7, end=107/7)
  mobilityWorkplace_test <- window(mobilityWorkplace, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_Workplace <- auto.arima(mobilityWorkplace_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyWorkplace_train))
  
  # predict
  forecast_Regression_ARMA_Workplace <- forecast(fit_Regression_ARMA_Workplace, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyWorkplace_mean,7)), h=7)
  
  # results rmse
  results_i=accuracy(forecast_Regression_ARMA_Workplace, mobilityWorkplace_test)
  results_i=cbind(c(paste(i,"train set"),paste(i,"test set")),results_i)
  workplace_rmse=rbind(workplace_rmse,results_i)
  # predictions 
  workplace_results=rbind(workplace_results,forecast_Regression_ARMA_Workplace$mean)
  
}




```


```{r}

workplace_results_table<-data.frame(matrix(unlist(workplace_results), ncol=7,byrow = F))     
workplace_results_table
workplace_results_table["State"]=state_list
workplace_results_table
colnames(workplace_results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")

write.csv(workplace_results_table,"Workplace_prediction7_all_States.csv")
```

```{r}
workplace_rmse_table<-data.frame(matrix(unlist(workplace_rmse), ncol=9,byrow = F))      

colnames(workplace_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

workplace_rmse_table
write.csv(workplace_rmse_table,"Workplaces_Rmse_all_States.csv")
```




```{r}
# parks 
parks_weights_df<-read.csv("parks_policy_scores.csv")

# test AL 

parks_results=list()
parks_rmse=list()
for (i in state_list){
  # get individual dataframe for each states
  data_frame_state<-df_us[which(df_us$a_state==i),]
  confirmed_cases<-ts(data_frame_state$confirmed_cases, start=1/7, frequency=7)
  confirmed_cases[confirmed_cases==0]<-1  # replace all 0 confirm to 1 for future log 
  confirmed_cases <- log(confirmed_cases)
  confirmed_cases_train <- window(confirmed_cases, start=1/7, end=100/7)
  confirmed_cases_test <- window(confirmed_cases, start=101/7, end=107/7)
  confirmed_cases_mean <- mean(confirmed_cases_test)
  # get weights
  state_weight=parks_weights_df[which(parks_weights_df$a_state==i),]
  policyParks <- ts(state_weight$policyScore_parks, start=1/7, frequency=7)
  policyParks_train <- window(policyParks, start=1/7, end=100/7)
  policyParks_test <- window(policyParks, start=101/7, end=107/7)
  policyParks_mean <- mean(policyParks_test)
# mobile data
  mobilityParks <- ts(data_frame_state$parks, start=1/7, end = 114/7, frequency=7)
  mobilityParks_train <- window(mobilityParks, start=8/7, end=107/7)
  mobilityParks_test <- window(mobilityParks, start=108/7, end=114/7)
  
  # model
  fit_Regression_ARMA_Parks <- auto.arima(mobilityParks_train, trace = TRUE, ic = 'aicc', xreg=cbind(confirmed_cases_train, policyParks_train))
  
  # predict
  forecast_Regression_ARMA_Parks <- forecast(fit_Regression_ARMA_Parks, xreg=cbind(rep(confirmed_cases_mean,7), rep(policyParks_mean,7)), h=7)
  
  # results rmse
  results_i=accuracy(forecast_Regression_ARMA_Parks, mobilityParks_test)
  results_i=cbind(c(paste(i,"train set"),paste(i,"test set")),results_i)
  parks_rmse=rbind(parks_rmse,results_i)
  # predictions 
  parks_results=rbind(parks_results,forecast_Regression_ARMA_Parks$mean)
  
}



```



```{r}
parks_results_table<-data.frame(matrix(unlist(parks_results), ncol=7,byrow = F))     
parks_results_table
parks_results_table["State"]=state_list
parks_results_table
colnames(parks_results_table)<-c("Day1","Day2","Day3","Day4","Day5","Day6","Day7","State")

write.csv(parks_results_table,"Parks_prediction7_all_States.csv")
```

```{r}
parks_rmse_table<-data.frame(matrix(unlist(parks_rmse), ncol=9,byrow = F))      

colnames(parks_rmse_table)<-c("State", 'ME', 'RMSE', 'MAE', 'MPE', 'MAPE', 'MASE', 'ACF1',"Theil's U")

parks_rmse_table
write.csv(parks_rmse_table,"Parks_Rmse_all_States.csv")
```






















